# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^frontend/src/languages/[^/]+/

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        name: ruff lint
        args: [--fix]
      - id: ruff
        name: ruff sort imports
        args: ["--select", "I", "--fix"]
      - id: ruff-format
        name: ruff format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Clean up trailing whitespace
      - id: trailing-whitespace

      # Ensure files have a proper EOL
      - id: end-of-file-fixer

      # All non-bat files should end with LF
      - id: mixed-line-ending
        name: Ensure LF endings on most files
        args: ["--fix=lf"]
        exclude: \.bat$

      # Bat files should be CRLF ending
      - id: mixed-line-ending
        name: Ensure CFLF endings on Windows files
        args: ["--fix=crlf"]
        files: \.bat$

      # Check for files that contain merge conflict strings
      - id: check-merge-conflict

      # Check for debugger imports and py37+ `breakpoint()` calls in python source
      - id: debug-statements

      # Check yaml files for parseable syntax
      - id: check-yaml

      # Prevent giant files from being committed
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args:
          - --configfile
          - bandit.yaml
        exclude: |
          (?x)^(
            .*/tests/.*|
            ^NOT-EXISTING-LAST-ENTRY$
          )$

  - repo: https://github.com/rbubley/mirrors-prettier/
    rev: v3.6.2
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|json|yaml|yml|md)$
        exclude: pnpm-lock.yaml
